import Head from "next/head";
import { Inter } from "next/font/google";
import RecipeCard from "@/components/recipe-card/RecipeCard";
import { fetchRecipes } from "@/services/fetchCategories";
import CategoryCard from "@/components/category-card/CategoryCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ categories = [] }) {
  return (
    <>
      <Head>
        <title>Yummy Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {categories.map((category) => (
          <CategoryCard category={category} />
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const data = await fetchRecipes();

  return {
    props: { categories: data.categories }, // will be passed to the page component as props
  };
}
