import Head from "next/head";
import styles from "./index.module.scss";
import { fetchRecipes } from "@/services/fetchCategories";
import { CategoryCard, Hero } from "@/components";

export default function Home({ categories = [] }) {
  return (
    <>
      <Head>
        <title>Yummy Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <div className={styles.categories}>
          {categories.map((category) => (
            <CategoryCard category={category} />
          ))}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const data = await fetchRecipes();

  return {
    props: { categories: data.categories }, // will be passed to the page component as props
  };
}
